export const DependencyContracts = {
	erc20: {
		AVAX: '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7',
		USDC: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
		ABI: [
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: 'spender', type: 'address' },
					{ internalType: 'uint256', name: 'subtractedValue', type: 'uint256' },
				],
				name: 'decreaseAllowance',
				outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'name',
				outputs: [
					{
						name: '',
						type: 'string',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{
						name: '_spender',
						type: 'address',
					},
					{
						name: '_value',
						type: 'uint256',
					},
				],
				name: 'approve',
				outputs: [
					{
						name: 'success',
						type: 'bool',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'totalSupply',
				outputs: [
					{
						name: '',
						type: 'uint256',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{
						name: '_from',
						type: 'address',
					},
					{
						name: '_to',
						type: 'address',
					},
					{
						name: '_value',
						type: 'uint256',
					},
				],
				name: 'transferFrom',
				outputs: [
					{
						name: 'success',
						type: 'bool',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'decimals',
				outputs: [
					{
						name: '',
						type: 'uint256',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'version',
				outputs: [
					{
						name: '',
						type: 'string',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: true,
				inputs: [
					{
						name: '_owner',
						type: 'address',
					},
				],
				name: 'balanceOf',
				outputs: [
					{
						name: 'balance',
						type: 'uint256',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'symbol',
				outputs: [
					{
						name: '',
						type: 'string',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{
						name: '_to',
						type: 'address',
					},
					{
						name: '_value',
						type: 'uint256',
					},
				],
				name: 'transfer',
				outputs: [
					{
						name: 'success',
						type: 'bool',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{
						name: '_spender',
						type: 'address',
					},
					{
						name: '_value',
						type: 'uint256',
					},
					{
						name: '_extraData',
						type: 'bytes',
					},
				],
				name: 'approveAndCall',
				outputs: [
					{
						name: 'success',
						type: 'bool',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				constant: true,
				inputs: [
					{
						name: '_owner',
						type: 'address',
					},
					{
						name: '_spender',
						type: 'address',
					},
				],
				name: 'allowance',
				outputs: [
					{
						name: 'remaining',
						type: 'uint256',
					},
				],
				payable: false,
				type: 'function',
			},
			{
				inputs: [
					{
						name: '_initialAmount',
						type: 'uint256',
					},
					{
						name: '_tokenName',
						type: 'string',
					},
					{
						name: '_decimalUnits',
						type: 'uint8',
					},
					{
						name: '_tokenSymbol',
						type: 'string',
					},
				],
				type: 'constructor',
			},
			{
				payable: false,
				type: 'fallback',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						name: '_from',
						type: 'address',
					},
					{
						indexed: true,
						name: '_to',
						type: 'address',
					},
					{
						indexed: false,
						name: '_value',
						type: 'uint256',
					},
				],
				name: 'Transfer',
				type: 'event',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						name: '_owner',
						type: 'address',
					},
					{
						indexed: true,
						name: '_spender',
						type: 'address',
					},
					{
						indexed: false,
						name: '_value',
						type: 'uint256',
					},
				],
				name: 'Approval',
				type: 'event',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: '_to', type: 'address' },
					{
						internalType: 'uint256',
						name: '_amount',
						type: 'uint256',
					},
				],
				name: 'mint',
				outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
		],
	},
	tokenPair: {
		USDC_LAVA: '0xecfa93907280c19aaf72b9f122b5d0cf4ecfd1a4',
		ABI: [
			{
				inputs: [],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'constructor',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'owner',
						type: 'address',
					},
					{
						indexed: true,
						internalType: 'address',
						name: 'spender',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'value',
						type: 'uint256',
					},
				],
				name: 'Approval',
				type: 'event',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'sender',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount0',
						type: 'uint256',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount1',
						type: 'uint256',
					},
					{
						indexed: true,
						internalType: 'address',
						name: 'to',
						type: 'address',
					},
				],
				name: 'Burn',
				type: 'event',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'sender',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount0',
						type: 'uint256',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount1',
						type: 'uint256',
					},
				],
				name: 'Mint',
				type: 'event',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'sender',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount0In',
						type: 'uint256',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount1In',
						type: 'uint256',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount0Out',
						type: 'uint256',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'amount1Out',
						type: 'uint256',
					},
					{
						indexed: true,
						internalType: 'address',
						name: 'to',
						type: 'address',
					},
				],
				name: 'Swap',
				type: 'event',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: false,
						internalType: 'uint112',
						name: 'reserve0',
						type: 'uint112',
					},
					{
						indexed: false,
						internalType: 'uint112',
						name: 'reserve1',
						type: 'uint112',
					},
				],
				name: 'Sync',
				type: 'event',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'from',
						type: 'address',
					},
					{
						indexed: true,
						internalType: 'address',
						name: 'to',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: 'value',
						type: 'uint256',
					},
				],
				name: 'Transfer',
				type: 'event',
			},
			{
				constant: true,
				inputs: [],
				name: 'DOMAIN_SEPARATOR',
				outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'MINIMUM_LIQUIDITY',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'PERMIT_TYPEHASH',
				outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [
					{ internalType: 'address', name: '', type: 'address' },
					{
						internalType: 'address',
						name: '',
						type: 'address',
					},
				],
				name: 'allowance',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: 'spender', type: 'address' },
					{
						internalType: 'uint256',
						name: 'value',
						type: 'uint256',
					},
				],
				name: 'approve',
				outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [{ internalType: 'address', name: '', type: 'address' }],
				name: 'balanceOf',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
				name: 'burn',
				outputs: [
					{ internalType: 'uint256', name: 'amount0', type: 'uint256' },
					{
						internalType: 'uint256',
						name: 'amount1',
						type: 'uint256',
					},
				],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'decimals',
				outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'factory',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'getReserves',
				outputs: [
					{ internalType: 'uint112', name: '_reserve0', type: 'uint112' },
					{
						internalType: 'uint112',
						name: '_reserve1',
						type: 'uint112',
					},
					{
						internalType: 'uint32',
						name: '_blockTimestampLast',
						type: 'uint32',
					},
				],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: '_token0', type: 'address' },
					{
						internalType: 'address',
						name: '_token1',
						type: 'address',
					},
				],
				name: 'initialize',
				outputs: [],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'kLast',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
				name: 'mint',
				outputs: [
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
				],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'name',
				outputs: [{ internalType: 'string', name: '', type: 'string' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [{ internalType: 'address', name: '', type: 'address' }],
				name: 'nonces',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: 'owner', type: 'address' },
					{
						internalType: 'address',
						name: 'spender',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
					{
						internalType: 'uint256',
						name: 'deadline',
						type: 'uint256',
					},
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{
						internalType: 'bytes32',
						name: 'r',
						type: 'bytes32',
					},
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'permit',
				outputs: [],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'price0CumulativeLast',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'price1CumulativeLast',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
				name: 'skim',
				outputs: [],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'uint256', name: 'amount0Out', type: 'uint256' },
					{
						internalType: 'uint256',
						name: 'amount1Out',
						type: 'uint256',
					},
					{ internalType: 'address', name: 'to', type: 'address' },
					{
						internalType: 'bytes',
						name: 'data',
						type: 'bytes',
					},
				],
				name: 'swap',
				outputs: [],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'symbol',
				outputs: [{ internalType: 'string', name: '', type: 'string' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [],
				name: 'sync',
				outputs: [],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'token0',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'token1',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: true,
				inputs: [],
				name: 'totalSupply',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				payable: false,
				stateMutability: 'view',
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: 'to', type: 'address' },
					{
						internalType: 'uint256',
						name: 'value',
						type: 'uint256',
					},
				],
				name: 'transfer',
				outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				constant: false,
				inputs: [
					{ internalType: 'address', name: 'from', type: 'address' },
					{
						internalType: 'address',
						name: 'to',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'value', type: 'uint256' },
				],
				name: 'transferFrom',
				outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
				payable: false,
				stateMutability: 'nonpayable',
				type: 'function',
			},
		],
	},
	traderjoe: {
		address: '0x60ae616a2155ee3d9a68541ba4544862310933d4',
		ABI: [
			{
				inputs: [
					{ internalType: 'address', name: '_factory', type: 'address' },
					{ internalType: 'address', name: '_WAVAX', type: 'address' },
				],
				stateMutability: 'nonpayable',
				type: 'constructor',
			},
			{
				inputs: [],
				name: 'WAVAX',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
					{ internalType: 'uint256', name: 'amountADesired', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBDesired', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'addLiquidity',
				outputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{
						internalType: 'uint256',
						name: 'amountTokenDesired',
						type: 'uint256',
					},
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAXMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'addLiquidityAVAX',
				outputs: [
					{ internalType: 'uint256', name: 'amountToken', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAX', type: 'uint256' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
				],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [],
				name: 'factory',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveOut', type: 'uint256' },
				],
				name: 'getAmountIn',
				outputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
				],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveOut', type: 'uint256' },
				],
				name: 'getAmountOut',
				outputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
				],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
				],
				name: 'getAmountsIn',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
				],
				name: 'getAmountsOut',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveA', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveB', type: 'uint256' },
				],
				name: 'quote',
				outputs: [
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
				],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'removeLiquidity',
				outputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAXMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'removeLiquidityAVAX',
				outputs: [
					{ internalType: 'uint256', name: 'amountToken', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAX', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAXMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'removeLiquidityAVAXSupportingFeeOnTransferTokens',
				outputs: [
					{ internalType: 'uint256', name: 'amountAVAX', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAXMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
					{ internalType: 'bool', name: 'approveMax', type: 'bool' },
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{ internalType: 'bytes32', name: 'r', type: 'bytes32' },
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'removeLiquidityAVAXWithPermit',
				outputs: [
					{ internalType: 'uint256', name: 'amountToken', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAX', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAVAXMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
					{ internalType: 'bool', name: 'approveMax', type: 'bool' },
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{ internalType: 'bytes32', name: 'r', type: 'bytes32' },
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'removeLiquidityAVAXWithPermitSupportingFeeOnTransferTokens',
				outputs: [
					{ internalType: 'uint256', name: 'amountAVAX', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
					{ internalType: 'bool', name: 'approveMax', type: 'bool' },
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{ internalType: 'bytes32', name: 'r', type: 'bytes32' },
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'removeLiquidityWithPermit',
				outputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapAVAXForExactTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactAVAXForTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactAVAXForTokensSupportingFeeOnTransferTokens',
				outputs: [],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForAVAX',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForAVAXSupportingFeeOnTransferTokens',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForTokensSupportingFeeOnTransferTokens',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountInMax', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapTokensForExactAVAX',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountInMax', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapTokensForExactTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{ stateMutability: 'payable', type: 'receive' },
		],
	},
	traderjoe_factory: {
		address: '0x9ad6c38be94206ca50bb0d90783181662f0cfa10',
		ABI: [
			{
				inputs: [
					{ internalType: 'address', name: '_feeToSetter', type: 'address' },
				],
				stateMutability: 'nonpayable',
				type: 'constructor',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'token0',
						type: 'address',
					},
					{
						indexed: true,
						internalType: 'address',
						name: 'token1',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'address',
						name: 'pair',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: '',
						type: 'uint256',
					},
				],
				name: 'PairCreated',
				type: 'event',
			},
			{
				inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				name: 'allPairs',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'allPairsLength',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
				],
				name: 'createPair',
				outputs: [{ internalType: 'address', name: 'pair', type: 'address' }],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [],
				name: 'feeTo',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'feeToSetter',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '', type: 'address' },
					{ internalType: 'address', name: '', type: 'address' },
				],
				name: 'getPair',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'migrator',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'pairCodeHash',
				outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [{ internalType: 'address', name: '_feeTo', type: 'address' }],
				name: 'setFeeTo',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '_feeToSetter', type: 'address' },
				],
				name: 'setFeeToSetter',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '_migrator', type: 'address' },
				],
				name: 'setMigrator',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
		],
	},
	swapsicle: {
		address: '0xc7f372c62238f6a5b79136a9e5d16a2fd7a3f0f5',
		ABI: [
			{
				inputs: [
					{ internalType: 'address', name: '_factory', type: 'address' },
					{ internalType: 'address', name: '_WETH', type: 'address' },
				],
				stateMutability: 'nonpayable',
				type: 'constructor',
			},
			{
				inputs: [],
				name: 'WETH',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
					{ internalType: 'uint256', name: 'amountADesired', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBDesired', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'addLiquidity',
				outputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{
						internalType: 'uint256',
						name: 'amountTokenDesired',
						type: 'uint256',
					},
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETHMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'addLiquidityETH',
				outputs: [
					{ internalType: 'uint256', name: 'amountToken', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETH', type: 'uint256' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
				],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [],
				name: 'factory',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveOut', type: 'uint256' },
				],
				name: 'getAmountIn',
				outputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
				],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveOut', type: 'uint256' },
				],
				name: 'getAmountOut',
				outputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
				],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
				],
				name: 'getAmountsIn',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
				],
				name: 'getAmountsOut',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveA', type: 'uint256' },
					{ internalType: 'uint256', name: 'reserveB', type: 'uint256' },
				],
				name: 'quote',
				outputs: [
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
				],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'removeLiquidity',
				outputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETHMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'removeLiquidityETH',
				outputs: [
					{ internalType: 'uint256', name: 'amountToken', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETH', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETHMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'removeLiquidityETHSupportingFeeOnTransferTokens',
				outputs: [
					{ internalType: 'uint256', name: 'amountETH', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETHMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
					{ internalType: 'bool', name: 'approveMax', type: 'bool' },
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{ internalType: 'bytes32', name: 'r', type: 'bytes32' },
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'removeLiquidityETHWithPermit',
				outputs: [
					{ internalType: 'uint256', name: 'amountToken', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETH', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'token', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountTokenMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountETHMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
					{ internalType: 'bool', name: 'approveMax', type: 'bool' },
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{ internalType: 'bytes32', name: 'r', type: 'bytes32' },
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'removeLiquidityETHWithPermitSupportingFeeOnTransferTokens',
				outputs: [
					{ internalType: 'uint256', name: 'amountETH', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
					{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountAMin', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountBMin', type: 'uint256' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
					{ internalType: 'bool', name: 'approveMax', type: 'bool' },
					{ internalType: 'uint8', name: 'v', type: 'uint8' },
					{ internalType: 'bytes32', name: 'r', type: 'bytes32' },
					{ internalType: 'bytes32', name: 's', type: 'bytes32' },
				],
				name: 'removeLiquidityWithPermit',
				outputs: [
					{ internalType: 'uint256', name: 'amountA', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountB', type: 'uint256' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapETHForExactTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactETHForTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactETHForTokensSupportingFeeOnTransferTokens',
				outputs: [],
				stateMutability: 'payable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForETH',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForETHSupportingFeeOnTransferTokens',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapExactTokensForTokensSupportingFeeOnTransferTokens',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountInMax', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapTokensForExactETH',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
					{ internalType: 'uint256', name: 'amountInMax', type: 'uint256' },
					{ internalType: 'address[]', name: 'path', type: 'address[]' },
					{ internalType: 'address', name: 'to', type: 'address' },
					{ internalType: 'uint256', name: 'deadline', type: 'uint256' },
				],
				name: 'swapTokensForExactTokens',
				outputs: [
					{ internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
				],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{ stateMutability: 'payable', type: 'receive' },
		],
	},
	swapsicle_factory: {
		address: '0x9C60C867cE07a3c403E2598388673C10259EC768',
		ABI: [
			{
				inputs: [
					{ internalType: 'address', name: '_feeToSetter', type: 'address' },
				],
				stateMutability: 'nonpayable',
				type: 'constructor',
			},
			{
				anonymous: false,
				inputs: [
					{
						indexed: true,
						internalType: 'address',
						name: 'token0',
						type: 'address',
					},
					{
						indexed: true,
						internalType: 'address',
						name: 'token1',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'address',
						name: 'pair',
						type: 'address',
					},
					{
						indexed: false,
						internalType: 'uint256',
						name: '',
						type: 'uint256',
					},
				],
				name: 'PairCreated',
				type: 'event',
			},
			{
				inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				name: 'allPairs',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'allPairsLength',
				outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: 'tokenA', type: 'address' },
					{ internalType: 'address', name: 'tokenB', type: 'address' },
				],
				name: 'createPair',
				outputs: [{ internalType: 'address', name: 'pair', type: 'address' }],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [],
				name: 'feeTo',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'feeToSetter',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'feeToStake',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '', type: 'address' },
					{ internalType: 'address', name: '', type: 'address' },
				],
				name: 'getPair',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'migrator',
				outputs: [{ internalType: 'address', name: '', type: 'address' }],
				stateMutability: 'view',
				type: 'function',
			},
			{
				inputs: [],
				name: 'pairCodeHash',
				outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
				stateMutability: 'pure',
				type: 'function',
			},
			{
				inputs: [{ internalType: 'address', name: '_feeTo', type: 'address' }],
				name: 'setFeeTo',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '_feeToSetter', type: 'address' },
				],
				name: 'setFeeToSetter',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '_feeToStake', type: 'address' },
				],
				name: 'setFeeToStake',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [
					{ internalType: 'address', name: '_migrator', type: 'address' },
				],
				name: 'setMigrator',
				outputs: [],
				stateMutability: 'nonpayable',
				type: 'function',
			},
		],
	},
}
